# Generated by Django 4.2.19 on 2025-02-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_created_by_remove_order_modified_by'),
        ('invoices', '0002_remove_invoiceitem_return_policy_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order',
        ),
        migrations.AddField(
            model_name='invoice',
            name='orders',
            field=models.ManyToManyField(to='orders.order'),
        ),
    ]
