# Generated by Django 4.2.19 on 2025-02-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_balance'),
        ('invoices', '0003_remove_invoice_order_invoice_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='suppliers.supplier'),
        ),
    ]
