# Generated by Django 4.2.19 on 2025-02-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='expired_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
