# Generated by Django 4.2.19 on 2025-02-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoicepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='previous_balance',
        ),
    ]
