# Generated by Django 4.2.19 on 2025-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_remove_invoice_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='expired_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
