# Generated by Django 4.2.19 on 2025-02-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_previous_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
