# Generated by Django 4.2.19 on 2025-02-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_expiry_date_product_expiry_period_and_more'),
        ('invoices', '0010_invoice_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='products.product'),
        ),
    ]
