# Generated by Django 4.2.19 on 2025-03-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoiceitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
