# Generated by Django 4.2.19 on 2025-03-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoiceitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
