# Generated by Django 4.2.19 on 2025-02-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='balance',
        ),
    ]
