# Generated by Django 4.2.19 on 2025-02-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_expiry_date_product_expiry_period_and_more'),
        ('orders', '0004_remove_order_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expiry_period',
            field=models.IntegerField(default=0, verbose_name='مدة انتهاء الصلاحية'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product'),
        ),
    ]
