# Generated by Django 4.2.19 on 2025-02-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_rename_balance_supplier_current_balance_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
